# Generated by Django 4.2.5 on 2023-10-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_events_user_department_user_regno_user_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
