# Generated by Django 4.2.5 on 2023-10-15 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_teamevents_userevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('order_id', models.CharField(max_length=500)),
                ('instamojo_response', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
    ]
