# Generated by Django 4.2.5 on 2023-10-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_userpayment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='order_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
