# Generated by Django 4.2.5 on 2023-10-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_userpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
