# Generated by Django 4.2.5 on 2023-10-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_userpayment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(null=True),
        ),
    ]
