# Generated by Django 4.2.5 on 2023-10-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_college'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
